### ISSUE TITLE
什么时候解决CutLetterDigitFilter不能用的bug？

### ISSUE THREAD

**Issue by baiyuang** [medcl/elasticsearch-analysis-mmseg#14]

**Comment by medcl** [comment]
Hi,能提供一下你问题的具体描述么?如何重现,具体细节.谢谢~

**Comment by medcl** [comment]
Hi,能提供一下你问题的具体描述么?如何重现,具体细节.谢谢~

**Comment by baiyuang** [comment]
具体细节如下：
首先，我在elasticsearch.xml中加入mmseg的配置
index:
  analysis:
    filter:
        mmseg_cut:
            type: mmseg 
    tokenizer:
        mmseg_max_word:
            type: mmseg
            seg_type: max_word
    analyzer:
        mmseg_max_word:
            type: custom
            tokenizer: mmseg_max_word
            filter: [mmseg_cut]
其中，mmseg_cut是一个filter，我在你的代码中添加了一个tokenFilter，返回的是CutLetterDigitFilter，使用会报异常！
因为你的代码中，analyzer和tokenizer都实现了，唯独tokenFilter没有实现，所以我问下什么时候解决！谢谢！

**Comment by medcl** [comment]
你的es是什么版本,我试试看

**Comment by medcl** [comment]
恩,文档有误,然后TokenFilter其实没有实现,TODO中

**Comment by baiyuang** [comment]
大神，你有没有qq或者其他邮件的，交流可以更方便。
我的qq是85985065，邮箱是85985065@qq.com！

**Comment by medcl** [comment]
欢迎加群: 190605846

**Comment by medcl** [comment]
fixed with commit 61b5e8199425c845a3060fe39f40e59868dd364b
