### ISSUE TITLE
mmseg插件安装完，elasticsearch启用失败

### ISSUE THREAD

**Issue by leavesbnw** [medcl/elasticsearch-analysis-mmseg#16]
## 系统环境
```shell
Linux ubuntu 3.13.0-66-generic #108-Ubuntu SMP Wed Oct 7 15:21:40 UTC 2015 i686 i686 i686 GNU/Linux
```
## 安装过程
下载官网最新的安装包，版本如下：
```shell
bin/elasticsearch --version
Version: 2.1.1, Build: 40e2c53/2015-12-15T13:05:55Z, JVM: 1.7.0_91
```
下载最新源码并编译，无错误信息，在target目录有如下内容：
```shell
drwxr-xr-x 8 root root  4096 Jan 16 04:25 ./
drwxr-xr-x 5 root root  4096 Jan 16 04:21 ../
drwxr-xr-x 2 root root  4096 Jan 16 04:25 archive-tmp/
drwxr-xr-x 4 root root  4096 Jan 16 04:22 classes/
-rw-r--r-- 1 root root 59244 Jan 16 04:22 elasticsearch-analysis-mmseg-1.7.0.jar
-rw-r--r-- 1 root root 33646 Jan 16 04:23 elasticsearch-analysis-mmseg-1.7.0-sources.jar
drwxr-xr-x 3 root root  4096 Jan 16 04:22 generated-sources/
drwxr-xr-x 2 root root  4096 Jan 16 04:22 maven-archiver/
drwxr-xr-x 2 root root  4096 Jan 16 04:25 releases/
drwxr-xr-x 2 root root  4096 Jan 16 04:25 surefire/
```
将`elasticsearch-analysis-mmseg-1.7.0.jar`拷贝到`/usr/share/elasticsearch/plugins/mmseg/`目录下。
下载最新的conf/mmseg，并将mmseg目录放在`/etc/elasticsearch/`目录下。
在文件`/etc/elasticsearch/elasticsearch.yml`中增加内容：
```shell
index:
  analysis: 
    analyzer:
      mmseg_maxword:
        type: custom
        filter:
        - lowercase
        tokenizer: mmseg_maxword
      mmseg_maxword_with_cut_letter_digi:
        type: custom
        filter:
        - lowercase
        - cut_letter_digit
        tokenizer: mmseg_maxword 
```
重启elasticsearch，发现elasticsearch启动不了。也就是说刚启动elasticsearch时，还存在elasticsearch进程，过一会儿elasticsearch进程就自动退出了，请问我哪儿配置错了么？

**Comment by medcl** [comment]
你应该拷贝release下面的zip包，解压到es对应目录就行，不用编辑配置文件

send via my Phone.

**Comment by leavesbnw** [comment]
请原谅我的愚笨，对于你所说的对应目录不是很明白什么意思？就拿我的情况为例吧。
解压`target/releases/elasticsearch-analysis-mmseg-1.7.0.zip`后：
```shell
ll  target/releases/
得到结果为：
drwxr-xr-x 3 root root   4096 Jan 16 07:45 ./
drwxr-xr-x 8 root root   4096 Jan 16 04:25 ../
drwxr-xr-x 3 root root   4096 Jan 13 11:15 config/
-rw-r--r-- 1 root root  59244 Jan 16 04:22 elasticsearch-analysis-mmseg-1.7.0.jar
-rw-r--r-- 1 root root 987564 Jan 16 07:04 elasticsearch-analysis-mmseg-1.7.0.zip
-rw-r--r-- 1 root root   2692 Jan 16 07:04 plugin-descriptor.properties
```
几种尝试，不分先后顺序：
1、我把config目录下的mmseg目录拷贝到/etc/elasticsearch/目录下，把elasticsearch-analysis-mmseg-1.7.0.jar和plugin-descriptor.properties拷贝到/usr/share/elasticsearch/plugins/目录下，重启elasticsearch，情况还是跟之前一样。
2、我把整个config目录拷贝到/etc/elasticsearch/目录下，把elasticsearch-analysis-mmseg-1.7.0.jar和plugin-descriptor.properties拷贝到/usr/share/elasticsearch/plugins/目录下，重启elasticsearch，情况还是跟之前一样。
3、我把config目录下的mmseg目录拷贝到/etc/elasticsearch/目录下，把elasticsearch-analysis-mmseg-1.7.0.jar和plugin-descriptor.properties拷贝到/usr/share/elasticsearch/plugins/mmseg/目录下，重启elasticsearch，情况还是跟之前一样。
4、我把整个config目录拷贝到/etc/elasticsearch/目录下，把elasticsearch-analysis-mmseg-1.7.0.jar和plugin-descriptor.properties拷贝到/usr/share/elasticsearch/plugins/mmseg/目录下，重启elasticsearch，情况还是跟之前一样。
5、我把整个config目录拷贝到/etc/elasticsearch/目录下，把elasticsearch-analysis-mmseg-1.7.0.jar和plugin-descriptor.properties拷贝到/usr/share/elasticsearch/plugins/elasticsearch-analysis-mmseg-1.7.0/目录下，重启elasticsearch，情况还是跟之前一样。
6、我把config目录下的mmseg目录拷贝到/etc/elasticsearch/目录下，把elasticsearch-analysis-mmseg-1.7.0.jar和plugin-descriptor.properties拷贝到/usr/share/elasticsearch/plugins/elasticsearch-analysis-mmseg-1.7.0/目录下，重启elasticsearch，情况还是跟之前一样。

不知道你说的对应是啥意思，还麻烦你能明示。

**Comment by medcl** [comment]
Hi,你不用拷贝配置文件，你直接看这个项目首页的安装说明，其他地方的安装说明不是最新的，另外你还可以参考这个项目，看里面是如何配置的：http://github.com/medcl/elasticsearch-rtf。

**Comment by leavesbnw** [comment]
谢谢您，问题解决了
