### ISSUE TITLE
关于字典的填加问题

### ISSUE THREAD

**Issue by leavesbnw** [medcl/elasticsearch-analysis-mmseg#17]
我听说elasticsearch-analysis-mmseg可以动态填加字典，mmseg/目录下有若干的字典，试问，哪个是关于停止词填加的文件？添加完之后，需要重启elasticsearch么？

**Comment by medcl** [comment]
mmseg本身不支持stopword，不过你可以结合stopfilter来使用，配置一个自定义的analyzer，tokenizer使用mmseg，tokenfilter配置一个stop filter，就可以达到你的要求，
https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-stop-tokenfilter.html
