### ISSUE TITLE
path.conf setting ignored

### ISSUE THREAD

**Issue by simonseed** [medcl/elasticsearch-analysis-mmseg#25]
https://www.elastic.co/guide/en/elasticsearch/reference/2.2/breaking_20_setting_changes.html#_custom_config_file

The es plugin install script will follow the path.conf setting and install config in to a customised location. 

But the analysis-mmseg plugin ignores this setting and assumes the config is installed in a directory inside plugin source location. 

So when using a custom config location the plugin fails. The work around is to symlink the config. But I think the plugin should read the config file location from properties.

Thanks

**Comment by medcl** [comment]
this plugin is not using `path.conf` config, custom config path is not supported, your config files must be stay with the plugin and under the `plugins/your-mmseg-plugin-name/config` folder.

**Comment by simonseed** [comment]
During the install process the official elasticsearch plugin script moves the config files to the directory pointed to by path.conf. So following the standard setup process will cause the plugin to fail when es is run if path.conf is set. Will you accept patches to fix this?

**Comment by medcl** [comment]
@simonseed your contribution is welcomed :)

**Comment by medcl** [comment]
fixed in master
