### ISSUE TITLE
question: how did you guys manage Chinese characters?

### ISSUE THREAD

**Issue by roylee0704** [medcl/elasticsearch-analysis-mmseg#28]
In English (ascii), a word is defined as anything that is separated by space, what about for Chinese character? :)

**Comment by medcl** [comment]
@roylee0704 There is no clear separator in Chinese

**Comment by roylee0704** [comment]
@medcl  ah, so each key contains exactly one Chinese character in a typical indexing database, I see.

**Comment by medcl** [comment]
fell free to reopen
