### ISSUE TITLE
打包出错

### ISSUE THREAD

**Issue by zonglinyue** [medcl/elasticsearch-analysis-mmseg#29]
[ERROR] Failed to execute goal on project elasticsearch-analysis-mmseg: Could not resolve dependencies for project org.elasticsearch:elasticsearch-analysis-mmseg:jar:1.9.1: Failed to collect dependencies for [org.elasticsearch:elasticsearch:jar:2.3.1 (compile), org.hamcrest:hamcrest-core:jar:1.3.RC2 (test), org.hamcrest:hamcrest-library:jar:1.3.RC2 (test)]: Failed to read artifact descriptor for org.elasticsearch:elasticsearch:jar:2.3.1: Could not transfer artifact org.elasticsearch:elasticsearch:pom:2.3.1 from/to oss.sonatype.org (http://oss.sonatype.org/content/repositories/releases/): oss.sonatype.org: 未知的名称或服务: Unknown host oss.sonatype.org: 未知的名称或服务 -> [Help 1]
请问应该怎么解决？

**Comment by zonglinyue** [comment]
sorry，I made a rookie mistake that use "mvn package" on Virtual Machine disconnected network.

**Comment by medcl** [comment]
@zonglinyue it's ok,closing now
