### ISSUE TITLE
ElasticsearchUncaughtExceptionHandler] [] fatal error in thread [main], exiting java.lang.NoClassDefFoundError: org/elasticsearch/index/analysis/AnalysisModule$AnalysisBinderProcessor

### ISSUE THREAD

**Issue by guybarnea** [medcl/elasticsearch-analysis-mmseg#33]
hi,
im trying to install a plugin on es v5.1.1 and get this error.
there is a way to solve it? tnx

**Comment by medcl** [comment]
Hi, @guybarnea 
May i know how did you installed the plugin?
You may checkout this example: https://github.com/medcl/elasticsearch-rtf/tree/master/plugins/analysis-mmseg

**Comment by guybarnea** [comment]
thanks.
our plugin workes fine in version 2.3.5.
we have to make changes in plugin's jar file , in order to secceeded install it in v5.1.1.
when we try to run the elasticsearch , we get this error.
do you have ani idea?

**Comment by medcl** [comment]
I have no idea what change you need to make, how about directly download from here:
https://github.com/medcl/elasticsearch-analysis-mmseg/releases/tag/v5.1.1
