### ISSUE TITLE
mmseg cause elasticsearch 5.2.0 shards unassigned

### ISSUE THREAD

**Issue by jayqie** [medcl/elasticsearch-analysis-mmseg#34]
我用elasticsearch 5.2.0 上的mmseg的时候，经常会出现mmseg导致shards unassigned的情况。
比如这个配置：
{
  "settings": {
    "number_of_shards": 3,
    "number_of_replicas": 1,
    "index.routing.allocation.include.cluster": "rec",
    "index.mapper.dynamic": false,
    "analysis": {
      "filter": {
        "stop_filter": {
          "type": "stop",
          "stopwords_path": "stopwords.txt",
          "ignore_case": true
        },
        "synonym_filter": {
          "type": "synonym",
          "synonyms_path": "synonyms.txt",
          "ignore_case": true,
          "expand": true
        }
      },
      "analyzer": {
        "text_auto": {
          "type": "custom",
          "tokenizer": "keyword",
          "filter": [
            "lowercase"
          ]
        },
        "text_complex": {
          "type": "custom",
          "tokenizer": "mmseg_complex",
          "filter": [
            "stop_filter",
            "synonym_filter",
            "lowercase"
          ]
        },
        "text_maxword": {
          "type": "custom",
          "tokenizer": "mmseg_maxword",
          "filter": [
            "stop_filter",
            "synonym_filter",
            "lowercase"
          ]
        },
        "standard_text": {
          "type": "custom",
          "tokenizer": "standard",
          "filter": [
            "lowercase"
          ]
        }
      }
    }
  },
在bulk 建索引的时候，会报这个错误：
[2017-02-15T11:54:11,011][DEBUG][o.e.a.b.TransportShardBulkAction] [datagrand-data-1] [duizhuang_v4][1] failed to execute bulk item (index) index {[duizhuang][duizhuang][878791], source[{"itemid": "878791", "last_update_time": 1487051295, "title": "H\u98d8\u5f69\u7ae5\u5b50\u4f5b\uff0c\u7389\u8d28\u7ec6\u817b\uff0c\u79cd\u8001\u7eaf\u51c0\u3002\u5b8c\u7f8e\uff0c\u4eae\u5ea6\u9ad8\uff0c\u54c1\u8d28\u7cbe\u54c1\uff01\u5c3a\u5bf840*16.3*6.6\u3002\u8d85\u503c\u63a8\u83508", "item_score": 333000.0, "price": 500000, "item_modify_time": 1486590407, "title1": "H\u98d8\u5f69\u7ae5\u5b50\u4f5b\uff0c\u7389\u8d28\u7ec6\u817b\uff0c\u79cd\u8001\u7eaf\u51c0\u3002\u5b8c\u7f8e\uff0c\u4eae\u5ea6\u9ad8\uff0c\u54c1\u8d28\u7cbe\u54c1\uff01\u5c3a\u5bf840*16.3*6.6\u3002\u8d85\u503c\u63a8\u83508", "create_time": 1486713188, "item_tags": "", "cateid": "2_13", "id": "878791"}]}
java.lang.NullPointerException: null

从而导致elasticsearch 的shards allocate失败，只剩一个primary replica可以work，
![error](https://cloud.githubusercontent.com/assets/2605076/22960152/a4e54bfa-f376-11e6-9678-4ff0ad2504e6.jpg)

点击unassigned的1分片，可以看到错误如下：
"details": "failed recovery, failure RecoveryFailedException[[duizhuang_v4][1]: Recovery failed from {datagrand-data-1}{de1cbfW0TT60i0I0WF9Dnw}{_8mhUy4DT4qwGXEEJLzf0w}{10.45.139.177}{10.45.139.177:9300}{cluster=rec, cpu=high, disk=low, cluster_awareness=rec, memory=high, ssd=yes} into {datagrand-data-3}{el9GeOaEREmcp_s33BX1YA}{DEFEaqphRhSCxqIdYtJJFw}{10.26.241.224}{10.26.241.224:9300}{cluster=rec, disk=low, cluster_awareness=rec, memory=medium, ssd=yes, cpu=high}]; nested: RemoteTransportException[[datagrand-data-1][10.45.139.177:9300][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[2] phase2 failed]; nested: RemoteTransportException[[datagrand-data-3][10.26.241.224:9300][internal:index/shard/recovery/translog_ops]]; nested: BatchOperationException[failed to apply batch translog operation]; nested: NullPointerException; ",

**Comment by medcl** [comment]
确定是 mmseg 的原因么，换其他分词没有问题是么？几个节点的环境？

**Comment by jayqie** [comment]
换ik是正常的。3个master node，4个data node，2个coord node。
之前搭过 1个master node，2个data node也出现过这个问题

**Comment by jayqie** [comment]
"mappings": {
    "app_name": {
      "dynamic": "strict",
      "properties": {
        "id": {
          "type": "string",
          "store": true,
          "index": "not_analyzed"
        },
        "itemid": {
          "type": "string",
          "store": true,
          "index": "not_analyzed"
        },
        "title": {
          "type": "text",
          "store": true,
          "index": true,
          "analyzer": "text_complex",
          "search_analyzer": "text_complex",
          "copy_to": ["search_text", "search4maxword_text"],
          "norms": false
        },
        "last_update_time": {
          "type": "long",
          "store": true,
          "index": "not_analyzed"
        },
        "item_modify_time": {
          "type": "long",
          "store": true,
          "index": "not_analyzed"
        },
        "create_time": {
          "type": "long",
          "store": true,
          "index": "not_analyzed"
        },
        "item_tags": {
          "type": "text",
          "store": true,
          "index": true,
          "analyzer": "text_complex",
          "search_analyzer": "text_complex",
          "copy_to": ["search_text1", "search4maxword_text1"],
          "norms": false
        },
        "cateid": {
          "type": "string",
          "store": true,
          "index": "not_analyzed",
          "norms": false
        },
        "price": {
          "type": "long",
          "store": true,
          "index": "not_analyzed"
        },
        "_version_": {
          "type": "long",
          "store": true,
          "index": "not_analyzed"
        },
        "item_score": {
          "type": "long",
          "store": true,
          "index": "not_analyzed"
        },
        "search_text": {
          "type": "text",
          "store": false,
          "index": true,
          "analyzer": "text_complex",
          "search_analyzer": "text_complex",
          "norms": false
        },
        "search_text1": {
          "type": "text",
          "store": false,
          "index": true,
          "analyzer": "text_complex",
          "search_analyzer": "text_complex",
          "norms": false
        },
        "search4maxword_text": {
          "type": "text",
          "store": false,
          "index": true,
          "analyzer": "text_maxword",
          "search_analyzer": "text_maxword",
          "norms": false
        },
        "search4maxword_text1": {
          "type": "text",
          "store": false,
          "index": true,
          "analyzer": "text_maxword",
          "search_analyzer": "text_maxword",
          "norms": false
        },
        "text": {
          "type": "text",
          "store": false,
          "index": true,
          "analyzer": "text_complex",
          "search_analyzer": "text_complex",
          "norms": false
        },
        "title1": {
          "type": "text",
          "store": false,
          "index": true,
          "analyzer": "standard_text",
          "search_analyzer": "standard_text",
          "norms": false
        }
      }
    }
  }
这边的配置是这样的，会不会是哪个配置导致的问题？
