### ISSUE TITLE
Did mmseg4j analyzer support synomy word filter?

### ISSUE THREAD

**Issue by Endeavour86** [medcl/elasticsearch-analysis-mmseg#37]
I searched Internet but there is nothing about synomy  filter configuration about mmesg4j.  if it exists how to config it ?

**Comment by medcl** [comment]
this plugin doesn't support config synonym filter directly， but you can custom a analyzer，combine mmseg analyzer and standard synonym filter。

https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-custom-analyzer.html

https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-synonym-graph-tokenfilter.html
